Repository OutSystems/outsystems-ui, pull requests merged in 2024-06, with the labels that each got.

#951 ROU-10768: update noUiSlider to latest - v15.7.2
  .gitattributes
  package.json
  src/scripts/Providers/OSUI/RangeSlider/NoUISlider/NoUiSliderEnum.ts
  src/scripts/Providers/OSUI/RangeSlider/NoUISlider/README.md
  src/scripts/Providers/OSUI/RangeSlider/NoUISlider/scss/_noUiSlider.scss
Labels: dependencies, chore

#952 ROU-10753: DropdownSearch and DropdownTags blurry issue.
  .vscode/settings.json
  src/scripts/Providers/OSUI/Dropdown/VirtualSelect/scss/_virtualselect.scss
Labels: bug

#953 ROU10687: DropdownServerSide style issues
  src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/scss/_dropdown-serverside.scss
Labels: bug, enhancement

#954 ROU-4248: Fix validation messages position
  src/scss/03-widgets/_form.scss
Labels: bug

#955 ROU-0 Update typedoc.json to fix error
  typedoc.json
Labels: bug, dependencies

#957 ROU-0: rollback TypeScript version back to 4.5.0
  package.json
Labels: bug, dependency

#958 ROU-0: rollback TypeScript and type doc versions
  package.json
Labels: bug, dependencies
