Repository OutSystems/outsystems-ui, pull requests merged in 2024-04, with the labels that each got.

#931 ROU-4863: fix balloon preview
  src/scripts/OSFramework/OSUI/Feature/Balloon/scss/_balloon.scss
Labels: bug

#935 ROU-4875: Update VirtualSelect library to the latest version v1.0.44
  .vscode/settings.json
  package.json
  src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelectEnum.ts
  src/scripts/Providers/OSUI/Dropdown/VirtualSelect/README.md
  src/scripts/Providers/OSUI/Dropdown/VirtualSelect/scss/_virtualselect_lib.scss
Labels: chore, dependency

#936 ROU-4865: Add SilentOnChangedEvent to DropdownClear API
  src/scripts/OutSystems/OSUI/Patterns/DropdownAPI.ts
  src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelect.ts
Labels: enhancement, chore

#934 ROU-4890: improve SectionIndex scroll behavior
  src/scripts/OSFramework/OSUI/Behaviors/Scroll.ts
  src/scripts/OSFramework/OSUI/GlobalEnum.ts
  src/scripts/OSFramework/OSUI/Helper/Dom.ts
  src/scripts/OSFramework/OSUI/Pattern/SectionIndex/ISectionIndex.ts
  src/scripts/OSFramework/OSUI/Pattern/SectionIndex/SectionIndex.ts
  src/scripts/OSFramework/OSUI/Pattern/SectionIndex/scss/_sectionindex.scss
  src/scripts/OSFramework/OSUI/Pattern/SectionIndexItem/Enum.ts
  src/scripts/OSFramework/OSUI/Pattern/SectionIndexItem/ISectionIndexItem.ts
  src/scripts/OSFramework/OSUI/Pattern/SectionIndexItem/SectionIndexItem.ts
Labels: bug
