Repository OutSystems/outsystems-ui, pull requests merged in 2024-08, with the labels that each got.

#975 ROU-10974: OverflowMenu - Fix A11Y attributes.
  src/scripts/OSFramework/OSUI/Constants.ts
  src/scripts/OSFramework/OSUI/Helper/ManageAccessibility.ts
  src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/DropdownServerSide.ts
  src/scripts/OSFramework/OSUI/Pattern/OverflowMenu/OverflowMenu.ts
Labels: bug

#974 ROU-10982: fix redraw callback on abstract provider pattern
  src/scripts/OSFramework/OSUI/Pattern/AbstractProviderPattern.ts
Labels: bug, chore

#972 ROU-10963: Fixed tab navigation inside sidebar.
  .vscode/settings.json
  src/scripts/OSFramework/OSUI/Behaviors/FocusTrap.ts
  src/scripts/OSFramework/OSUI/Constants.ts
  src/scripts/OSFramework/OSUI/Helper/Dom.ts
  src/scripts/OSFramework/OSUI/Pattern/AccordionItem/AccordionItem.ts
  src/scripts/OSFramework/OSUI/Pattern/BottomSheet/BottomSheet.ts
  src/scripts/OSFramework/OSUI/Pattern/FlipContent/FlipContent.ts
  src/scripts/OSFramework/OSUI/Pattern/OverflowMenu/OverflowMenu.ts
  src/scripts/OSFramework/OSUI/Pattern/Progress/AbstractProgress.ts
  src/scripts/OSFramework/OSUI/Pattern/Rating/Rating.ts
  src/scripts/OSFramework/OSUI/Pattern/Sidebar/Sidebar.ts
  src/scripts/OSFramework/OSUI/Pattern/Submenu/Submenu.ts
  src/scripts/OSFramework/OSUI/Pattern/TabsContentItem/TabsContentItem.ts
  src/scripts/OSFramework/OSUI/Pattern/TabsHeaderItem/TabsHeaderItem.ts
  src/scripts/OSFramework/OSUI/Pattern/Tooltip/Tooltip.ts
Labels: bug

#978 ROU-11016: Fix SetMenuIconListeners
  src/scripts/OutSystems/OSUI/Utils/Menu.ts
Labels: bug

#979 ROU-11042: fix button-group validation message
  src/scss/03-widgets/_button-group.scss
  src/scss/O11.OutSystemsUI.scss
  src/scss/ODC.OutSystemsUI.scss
Labels: bug, chore

#981 ROU-11057: Update VirtualSelect library to the latest version v1.0.45
  .vscode/settings.json
  package.json
  src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelectEnum.ts
  src/scripts/Providers/OSUI/Dropdown/VirtualSelect/README.md
  src/scripts/Providers/OSUI/Dropdown/VirtualSelect/scss/_virtualselect_lib.scss
Labels: chore, dependency

#983 ROU-11113: DatePicker - Fix DatePicker and DatePickerRange hidden input visibility
  src/scripts/OSFramework/OSUI/Pattern/DatePicker/scss/_datepicker.scss
Labels: bug
