Repository OutSystems/outsystems-ui, pull requests merged in 2024-05, with the labels that each got.

#939 ROU-4738: Add Balloon Feature to Tooltip and Dropdown
  .vscode/settings.json
  package.json
  src/scripts/Global.d.ts
  src/scripts/OSFramework/OSUI/Behaviors/FocusTrap.ts
  src/scripts/OSFramework/OSUI/Feature/Balloon/Balloon.ts
  src/scripts/OSFramework/OSUI/Feature/Balloon/Enum.ts
  src/scripts/OSFramework/OSUI/Feature/Balloon/scss/_balloon.scss
  src/scripts/OSFramework/OSUI/GlobalEnum.ts
  src/scripts/OSFramework/OSUI/Helper/BoundPosition.ts
  src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/DropdownServerSide.ts
  src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/DropdownServerSideEnum.ts
  src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/scss/_dropdown-serverside.scss
  src/scripts/OSFramework/OSUI/Pattern/DropdownServerSideItem/Enum.ts
  src/scripts/OSFramework/OSUI/Pattern/OverflowMenu/OverflowMenu.ts
  src/scripts/OSFramework/OSUI/Pattern/Tooltip/Enum.ts
  src/scripts/OSFramework/OSUI/Pattern/Tooltip/Tooltip.ts
  src/scripts/OSFramework/OSUI/Pattern/Tooltip/scss/_tooltip.scss
  src/scripts/OSFramework/OSUI/Utils/FloatingPosition/FloatingPositionConfigs.ts
  src/scripts/Providers/OSUI/Utils/FloatingUI/Enum.ts
  src/scripts/Providers/OSUI/Utils/FloatingUI/FloatingUI.ts
  src/scripts/Providers/OSUI/Utils/FloatingUI/README.md
Labels: bug, enhancement

#943 ROU-4770: Fix Dropdown Server Side issues after integrating the OSUI Balloon
  src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/scss/_dropdown-serverside.scss
  src/scripts/OSFramework/OSUI/Pattern/Tabs/scss/_tabs.scss
Labels: bug

#945 ROU-4738-v2: fix drop and tooltip issues
  src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/scss/_dropdown-serverside.scss
  src/scripts/OSFramework/OSUI/Pattern/Tabs/scss/_tabs.scss
  src/scripts/OSFramework/OSUI/Pattern/Tooltip/Tooltip.ts
Labels: bug

#946 ROU-0 - Update version to 2.19.0
  README.md
  gulp/ProjectSpecs/DefaultSpecs.js
  package.json
  src/scripts/OSFramework/OSUI/Constants.ts
  src/scss/O11.OutSystemsUI.scss
  src/scss/ODC.OutSystemsUI.scss
Labels: chore

#947 ROU-10751: TabsContent is not visible at DesignTime
  src/scripts/OSFramework/OSUI/Pattern/Tabs/scss/_tabs.scss
  src/scss/O11.OutSystemsUI.scss
  src/scss/ODC.OutSystemsUI.scss
Labels: bug

#950 ROU-0: Update dev-dependencies
  .vscode/settings.json
  package.json
Labels: dependencies, chore

#948 ROU-4825: Prevent multiple redraws.
  src/scripts/OSFramework/OSUI/Helper/AsyncInvocation.ts
  src/scripts/OSFramework/OSUI/Pattern/AbstractProviderPattern.ts
Labels: enhancement
