Repository OutSystems/outsystems-ui, pull requests merged in 2025-04, with the labels that each got.

#1029 ROU-11742: Fix lint issue
  src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelectConfig.ts
Labels: bug

#1031 ROU-11808: Update Virtual Select provider to v1.0.49
  package.json
  src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelectEnum.ts
  src/scripts/Providers/OSUI/Dropdown/VirtualSelect/README.md
  src/scripts/Providers/OSUI/Dropdown/VirtualSelect/scss/_virtualselect_lib.scss
Labels: bug, dependency

#1032 ROU-11784: Review how ariaLabel is being set to the DropdownSearch and DropdownTags
  src/scripts/Providers/OSUI/Dropdown/VirtualSelect/AbstractVirtualSelect.ts
  src/scripts/Providers/OSUI/Dropdown/VirtualSelect/Search/VirtualSelectSearch.ts
  src/scripts/Providers/OSUI/Dropdown/VirtualSelect/Search/VirtualSelectSearchConfig.ts
  src/scripts/Providers/OSUI/Dropdown/VirtualSelect/Tags/VirtualSelectTags.ts
  src/scripts/Providers/OSUI/Dropdown/VirtualSelect/Tags/VirtualSelectTagsConfig.ts
  src/scripts/Providers/OSUI/Dropdown/VirtualSelect/VirtualSelect.d.ts
Labels: bug, enhancement

#1033 ROU-11858: Improve error handling for scenarios without TabsHeaderItem/TabsContentItem
  src/scripts/OSFramework/OSUI/ErrorCodes.ts
  src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts
Labels: enhancement

#1035 ROU-11858: Improve error handling on Tabs
  src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts
Labels: chore

#1034 ROU-11827: SubMenu, Date and Time Pickers A11Y improvements.
  src/scripts/OSFramework/OSUI/GlobalEnum.ts
  src/scripts/OSFramework/OSUI/Pattern/Submenu/Submenu.ts
  src/scripts/Providers/OSUI/Datepicker/Flatpickr/AbstractFlatpickr.ts
  src/scripts/Providers/OSUI/Timepicker/Flatpickr/FlatpickrTime.ts
Labels: bug, enhancement
