Repository OutSystems/outsystems-ui, pull requests merged in 2025-05, with the labels that each got.

#1036 ROU-11864: Fix tab indicator incorrect positioning
  src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts
Labels: bug

#1038 ROU-11492: Refactoring workflows and GH Actions
  .github/os-git-actions/manual-commit/action.yml
  .github/os-git-actions/setup-gpg/action.yml
  .github/os-git-actions/signed-commit/action.yml
  .github/workflows/PreRelease.yml
  .github/workflows/Release.yml
  .github/workflows/build.yaml
  .github/workflows/create-n-deploy-docs.yaml
  .github/workflows/create-n-deploy-npm.yaml
  .github/workflows/manage-docs.yaml
  .github/workflows/manage-npm.yaml
  .github/workflows/pre-release.yaml
  .github/workflows/release.yaml
  .github/workflows/validate-pr-labels.yaml
  .github/workflows/validate-pr-labels.yml
  .github/workflows/validate-pr-title.yaml
  .github/workflows/validate-pr-title.yml
Labels: do not merge, chore

#1042 ROU-11919: Increment version and add styles for dropdowns
  README.md
  gulp/ProjectSpecs/DefaultSpecs.js
  package.json
  src/scripts/OSFramework/OSUI/Constants.ts
  src/scripts/OSFramework/OSUI/Pattern/AnimatedLabel/AnimatedLabel.ts
  src/scripts/Providers/OSUI/Dropdown/VirtualSelect/scss/_virtualselect.scss
  src/scss/O11.OutSystemsUI.scss
  src/scss/ODC.OutSystemsUI.scss
Labels: enhancement, chore
